<?php

/**
 * Human-approved V1 content for departments that previously lacked frameworks.
 *
 * The wording is Vytte-authored and source-informed; no source instrument is reproduced.
 * Approved for publication on 31 July 2026 under the official content lifecycle.
 */
return [
    'sources' => [
        'WHO_HHFA' => ['Harmonized Health Facility Assessment (HHFA)', 'World Health Organization', 'Standardized facility service availability, readiness, quality, management and finance assessment.', 'https://www.who.int/data/data-collection-tools/harmonized-health-facility-assessment'],
        'WHO_ECT' => ['Emergency Care Toolkit', 'World Health Organization', 'Triage, resuscitation, emergency documentation, referral and counter-referral tools.', 'https://www.who.int/teams/integrated-health-services/clinical-services-and-systems/emergency-and-critical-care/emergency-care-toolkit'],
        'WHO_ECO' => ['Essential resources for emergency, critical and operative care', 'World Health Organization', 'Planning and assessment resources for emergency, critical and operative care.', 'https://www.who.int/teams/integrated-health-services/clinical-services-and-systems/emergency--critical-and-operative-care/essential-resources-for-emergency--critical-and-operative-care'],
        'WHO_SURGERY' => ['WHO Surgical Safety Checklist and safe surgery resources', 'World Health Organization', 'Core perioperative safety processes, teamwork and surgical quality improvement.', 'https://www.who.int/teams/integrated-health-services/quality-of-care-and-patient-safety/patient-safety-guidance-and-tools/safe-surgery/tool-and-resources'],
        'WHO_MATERNAL_QOC' => ['Standards for improving quality of maternal and newborn care in health facilities', 'World Health Organization', 'Quality standards for care around childbirth.', 'https://www.who.int/publications/i/item/9789241511216'],
        'WHO_PNC' => ['WHO recommendations on maternal and newborn care for a positive postnatal experience', 'World Health Organization', 'Routine postnatal care for women and newborns in facilities and communities.', 'https://www.who.int/publications/i/item/9789240045989'],
        'WHO_FP' => ['Family planning: a global handbook for providers, 4th edition', 'World Health Organization and Johns Hopkins CCP', 'Evidence-based, rights-respecting provision of contraceptive information and services.', 'https://www.who.int/publications/i/item/family-planning---a-global-handbook-for-providers'],
        'WHO_PEN' => ['WHO package of essential noncommunicable disease interventions for primary health care', 'World Health Organization', 'Integrated NCD detection and management in resource-limited primary care.', 'https://www.who.int/publications/b/54566'],
        'WHO_ADOLESCENT' => ['Global standards for quality health-care services for adolescents', 'World Health Organization and UNAIDS', 'Standards and criteria for accessible, acceptable, equitable and effective adolescent care.', 'https://www.who.int/publications/i/item/9789241549332/'],
        'WHO_REHAB' => ['Rehabilitation in health systems: guide for action', 'World Health Organization', 'Accessible, integrated, multidisciplinary rehabilitation services and monitoring.', 'https://www.who.int/publications/i/item/rehabilitation-in-health-systems-guide-for-action'],
        'WHO_PALLIATIVE' => ['Quality health services and palliative care', 'World Health Organization', 'Practical approaches to effective, safe, person-centred and integrated palliative care.', 'https://www.who.int/publications/i/item/9789240035164'],
        'WHO_AMS' => ['Antimicrobial stewardship programmes in health-care facilities in low- and middle-income countries', 'World Health Organization', 'Core facility structures and interventions for responsible antimicrobial use.', 'https://www.who.int/publications-detail-redirect/9789241515481'],
        'WHO_DISABILITY' => ['Disability-inclusive health services toolkit', 'World Health Organization', 'Practical guidance for removing physical, communication and attitudinal barriers to care.', 'https://www.who.int/publications/i/item/9789290618928'],
        'WHO_ICOPE' => ['Integrated care for older people implementation framework', 'World Health Organization', 'Person-centred integrated care responding to older people’s intrinsic capacity and functional needs.', 'https://www.who.int/publications/i/item/9789241515993'],
        'WHO_EYE_PECI' => ['Package of eye care interventions', 'World Health Organization', 'Evidence-based eye-care interventions and the resources required across the continuum of care.', 'https://www.who.int/publications/i/item/9789240048959'],
        'WHO_ORAL' => ['Global strategy and action plan on oral health 2023–2030', 'World Health Organization', 'Integrated essential oral-health promotion, prevention, treatment and monitoring.', 'https://www.who.int/publications/i/item/9789240090538/'],
        'WHO_OUTBREAK' => ['Framework and toolkit for IPC in outbreak preparedness, readiness and response at health-care facility level', 'World Health Organization', 'Facility-level preparedness, readiness, response and continuity during outbreaks.', 'https://www.who.int/publications/i/item/9789240051027'],
        'WHO_CLIMATE_HCF' => ['WHO guidance for climate-resilient and environmentally sustainable health care facilities', 'World Health Organization', 'Facility resilience across workforce, WASH, energy, infrastructure, technology and products.', 'https://www.who.int/publications/i/item/9789240012226'],
        'WHO_OHS_HCW' => ['Caring for those who care: occupational health and safety programmes for health workers', 'World Health Organization and International Labour Organization', 'Facility-level occupational health and safety programme elements for health workers.', 'https://www.who.int/publications-detail-redirect/9789240040779'],
        'WHO_NTD_2030' => ['Ending the neglect to attain the Sustainable Development Goals: NTD road map 2021–2030', 'World Health Organization', 'Integrated NTD case management, surveillance, disability prevention and health-system delivery.', 'https://www.who.int/publications/b/53673'],
        'WHO_BLOOD' => ['Blood safety and availability', 'World Health Organization', 'Safe donor selection, screening, processing, storage, compatibility, appropriate use and haemovigilance.', 'https://www.who.int/en/news-room/fact-sheets/detail/blood-safety-and-availability'],
        'IAEA_RAD_QA' => ['Handbook of Basic Quality Control Tests for Diagnostic Radiology', 'International Atomic Energy Agency', 'Quality assurance, equipment testing, image quality and radiation protection in diagnostic radiology.', 'https://www.iaea.org/publications/14890/handbook-of-basic-quality-control-tests-for-diagnostic-radiology'],
    ],

    'departments' => [
        'OPD' => ['domain' => 'SERV', 'source' => 'WHO_HHFA', 'questions' => [
            'Does the outpatient service use a consistent process to identify and prioritize patients who need urgent attention?',
            'Are current clinical protocols available at the point of care for the common conditions managed in outpatient services?',
            'Can outpatient consultations be conducted with visual and auditory privacy?',
            'Is the essential examination and diagnostic equipment expected for outpatient care functional and available?',
            'Are follow-up needs, return instructions and referrals recorded before the patient leaves outpatient care?',
            'Is there a defined process to recognize and escalate a patient whose condition deteriorates while waiting or receiving outpatient care?',
        ]],
        'REF' => ['domain' => 'SERV', 'source' => 'WHO_ECT', 'questions' => [
            'Are written referral criteria and referral pathways available for conditions the facility cannot manage?',
            'Is a standardized referral form used to communicate the patient’s condition, treatment given and reason for referral?',
            'Are patients assessed and stabilized as far as possible before an urgent transfer?',
            'Can staff reliably contact the receiving facility before or during an urgent referral?',
            'Is suitable transport available or formally arranged for patients who require transfer?',
            'Are referral outcomes and counter-referral information recorded and reviewed to improve continuity of care?',
        ]],
        'IPD' => ['domain' => 'SERV', 'source' => 'WHO_HHFA', 'questions' => [
            'Are written admission, transfer and discharge criteria used for the inpatient services provided?',
            'Are vital signs and clinical reviews recorded at a frequency appropriate to each inpatient’s condition?',
            'Is every administered medicine recorded against an authorized prescription and the correct patient?',
            'Is there a defined escalation process for an inpatient whose condition deteriorates?',
            'Is clinically qualified cover available whenever patients are admitted to the ward?',
            'Does discharge planning document medicines, warning signs, follow-up arrangements and any continuing care needs?',
        ]],
        'LBD' => ['domain' => 'SERV', 'source' => 'WHO_MATERNAL_QOC', 'questions' => [
            'Is a skilled birth attendant available whenever the facility accepts women in labour?',
            'Is labour progress and the condition of the woman and baby monitored with a structured record?',
            'Are essential medicines, supplies and functional equipment for obstetric and newborn emergencies immediately available?',
            'Are current protocols available for postpartum haemorrhage, hypertensive emergencies and newborn resuscitation?',
            'Are privacy, dignity, informed communication and respectful maternity care protected throughout labour and birth?',
            'Is there a tested process for urgent referral or transfer when complications exceed the facility’s capacity?',
        ]],
        'PNC' => ['domain' => 'SERV', 'source' => 'WHO_PNC', 'questions' => [
            'Do the woman and newborn receive documented postnatal assessments before discharge?',
            'Are maternal and newborn danger signs checked and acted on during postnatal contacts?',
            'Is practical breastfeeding support available before discharge and during follow-up?',
            'Do families receive understandable counselling on danger signs, newborn care and postpartum family planning?',
            'Are postnatal follow-up contacts scheduled and linked to community care where available?',
            'Is there a clear referral pathway for maternal or newborn complications identified after birth?',
        ]],
        'FP' => ['domain' => 'SERV', 'source' => 'WHO_FP', 'questions' => [
            'Is a range of contraceptive methods routinely available so clients can make a meaningful choice?',
            'Does counselling support informed and voluntary choice without pressure or discrimination?',
            'Can family-planning counselling and care be provided with privacy and confidentiality?',
            'Do providers use current eligibility guidance and explain expected effects, side effects and warning signs?',
            'Are contraceptive stock levels and stock-outs monitored with timely resupply action?',
            'Is follow-up or referral available for side effects, complications, method switching or removal?',
        ]],
        'SRH' => ['domain' => 'SERV', 'source' => 'WHO_FP', 'questions' => [
            'Does the facility provide or formally refer for an essential package of sexual and reproductive health services?',
            'Are sexual and reproductive health services confidential, non-discriminatory and accessible to eligible clients?',
            'Are protocols and referral pathways available for sexually transmitted infection assessment and management?',
            'Is cervical cancer screening or an established referral pathway available for eligible clients?',
            'Can staff provide first-line support and safe referral for clients affected by sexual or gender-based violence?',
            'Are trained providers, current job aids and essential commodities available for the sexual and reproductive health services offered?',
        ]],
        'NCD' => ['domain' => 'SERV', 'source' => 'WHO_PEN', 'questions' => [
            'Are current protocols used for detecting and managing hypertension, diabetes and other common noncommunicable diseases?',
            'Are functional blood-pressure, blood-glucose and other basic NCD assessment tools available?',
            'Are the essential medicines expected for the NCD services offered routinely available?',
            'Is cardiovascular risk assessed and used to guide care for eligible patients?',
            'Is there a system to recall, follow up and monitor people receiving long-term NCD care?',
            'Do NCD consultations include practical support for tobacco cessation, healthy diet, physical activity and medicine adherence?',
        ]],
        'ICU' => ['domain' => 'SERV', 'source' => 'WHO_ECO', 'questions' => [
            'Are written admission, escalation, transfer and discharge criteria used for intensive or high-dependency care?',
            'Is appropriately trained clinical cover available at all times for occupied critical-care beds?',
            'Are oxygen, suction, monitoring and resuscitation equipment functional and immediately available?',
            'Are evidence-based practices used to reduce infections associated with invasive devices and critical care?',
            'Are emergency medicines, equipment and safety checks completed and documented at defined intervals?',
            'Are critical-care outcomes, adverse events and unexpected deaths reviewed for improvement?',
        ]],
        'REH' => ['domain' => 'SERV', 'source' => 'WHO_REHAB', 'questions' => [
            'Does rehabilitation begin with a documented assessment of functioning and a goal-based care plan?',
            'Are appropriately trained rehabilitation professionals available for the services the facility claims to provide?',
            'Are essential rehabilitation equipment and assistive products functional and available?',
            'Are referral and continuity arrangements in place across inpatient, outpatient, community and higher-level rehabilitation services?',
            'Are patients and families involved in setting rehabilitation goals and planning self-management?',
            'Are changes in functioning and participation measured and used to review the rehabilitation plan?',
        ]],
        'PAL' => ['domain' => 'PCOM', 'source' => 'WHO_PALLIATIVE', 'questions' => [
            'Is there a process to identify patients who may benefit from palliative care early in the course of serious illness?',
            'Are pain and other distressing physical symptoms assessed and documented using a consistent approach?',
            'Are essential symptom-control medicines, including lawfully managed controlled medicines where applicable, available?',
            'Are patients and families supported to understand options, express preferences and participate in care decisions?',
            'Can the service address or refer psychological, social, spiritual and caregiver-support needs?',
            'Are continuity arrangements available across facility, home and community care, including support around dying and bereavement?',
        ]],
        'AMR' => ['domain' => 'SAFE', 'source' => 'WHO_AMS', 'questions' => [
            'Is a named team or accountable person responsible for antimicrobial stewardship in the facility?',
            'Are current antimicrobial treatment guidelines readily available to prescribers?',
            'Does the facility use practical stewardship controls such as formulary guidance, review or authorization for selected antimicrobials?',
            'Is antimicrobial prescribing or consumption monitored using available facility data?',
            'Are microbiology, susceptibility or other diagnostic results used to improve antimicrobial selection where available?',
            'Do prescribers receive education and feedback on antimicrobial use and resistance?',
        ]],
        'DIS' => ['domain' => 'PCOM', 'source' => 'WHO_DISABILITY', 'questions' => [
            'Can people with mobility limitations enter, move through and use the essential services of the facility?',
            'Is health information available in communication formats that can be understood by people with different disabilities?',
            'Can the facility make reasonable adjustments to appointments, examination and care when a person needs them?',
            'Are staff trained to provide respectful, non-discriminatory and disability-inclusive care?',
            'Does the facility collect feedback or access information that can identify barriers experienced by people with disabilities?',
            'Are referral links available for rehabilitation, assistive products and other disability-related support?',
        ]],
        'HPR' => ['domain' => 'PCOM', 'source' => 'WHO_HHFA', 'questions' => [
            'Does the facility have a health-promotion plan linked to the main health needs of its patients and community?',
            'Are health-education materials understandable, culturally appropriate and available in relevant languages or formats?',
            'Do routine patient encounters include counselling relevant to prevention, treatment adherence and self-care?',
            'Are health-promotion or outreach activities delivered according to a documented schedule?',
            'Are patients or community representatives involved in shaping health-promotion priorities and messages?',
            'Does the facility monitor who health-promotion activities reach and whether priority behaviours or knowledge improve?',
        ]],
        'EYE' => ['domain' => 'SERV', 'source' => 'WHO_EYE_PECI', 'questions' => [
            'Can the service perform and record a standardized visual-acuity assessment?',
            'Is the essential equipment for the eye-care interventions offered functional and available?',
            'Are current protocols available for common eye conditions and urgent warning signs?',
            'Is there a clear referral pathway for eye conditions that require services not available at this facility?',
            'Are infection-prevention and instrument-reprocessing practices applied to eye examinations and procedures?',
            'Are treatment, referral and follow-up outcomes documented for people receiving eye care?',
        ]],
        'ORL' => ['domain' => 'SERV', 'source' => 'WHO_ORAL', 'questions' => [
            'Does the facility provide or formally refer for essential preventive, urgent and basic restorative oral-health care?',
            'Are dental instruments cleaned, sterilized and stored through a documented safe process?',
            'Is the essential dental equipment used by the service functional and maintained?',
            'Are current protocols available for dental pain, infection, trauma and other common oral conditions?',
            'Are oral-cancer risk signs recognized and linked to a defined referral pathway?',
            'Are oral-health findings, treatment, advice and follow-up needs recorded for each patient?',
        ]],
        'OLD' => ['domain' => 'PCOM', 'source' => 'WHO_ICOPE', 'questions' => [
            'Are older people assessed for changes in mobility, nutrition, vision, hearing, cognition and mood when indicated?',
            'Are identified needs brought together in a person-centred care plan with agreed goals?',
            'Are medicines reviewed for duplication, interactions, inappropriate use and adherence challenges?',
            'Are falls risk and environmental safety assessed with action taken when risks are found?',
            'Are caregiver needs, social support and protection concerns considered in care planning?',
            'Are older people linked to appropriate specialist, rehabilitation, community and social-care services?',
        ]],
        'OBR' => ['domain' => 'SAFE', 'source' => 'WHO_OUTBREAK', 'questions' => [
            'Does the facility have a current outbreak preparedness and response plan with named roles?',
            'Can the facility detect and promptly report priority syndromes, unusual events and notifiable diseases?',
            'Is there a practical process to screen, separate and safely manage potentially infectious patients?',
            'Are essential outbreak supplies and personal protective equipment monitored and accessible?',
            'Have relevant staff received outbreak-response training or participated in a drill within the planned review period?',
            'Does the plan address continuity of essential services and communication with staff, patients and the community?',
        ]],
        'ENV' => ['domain' => 'RES', 'source' => 'WHO_CLIMATE_HCF', 'questions' => [
            'Has the facility assessed its exposure and vulnerability to locally relevant climate and environmental hazards?',
            'Does the facility have continuity arrangements for water, energy and essential services during climate-related disruption?',
            'Has critical infrastructure and equipment been protected against the main local hazards identified?',
            'Does the facility monitor energy, water or other resource use and act on avoidable waste?',
            'Are health-care waste and hazardous releases managed to protect staff, patients and the surrounding environment?',
            'Are staff prepared for the health and operational effects of locally relevant climate emergencies?',
        ]],
        'OCC' => ['domain' => 'WORK', 'source' => 'WHO_OHS_HCW', 'questions' => [
            'Does the facility have an occupational health and safety programme based on a current workplace risk assessment?',
            'Can health workers access recommended vaccination and occupational health services?',
            'Is there a confidential process to report occupational exposures and obtain timely assessment and post-exposure care?',
            'Are personal protective equipment and safe work procedures available for the hazards staff encounter?',
            'Does the facility address violence, psychosocial strain, manual handling and other non-infectious workplace hazards?',
            'Are occupational injuries and illnesses reviewed and followed by documented corrective action?',
        ]],
        'NTD' => ['domain' => 'SERV', 'source' => 'WHO_NTD_2030', 'questions' => [
            'Are current case definitions or job aids available for the neglected tropical diseases relevant to the facility’s catchment?',
            'Are relevant staff able to recognize, initially manage and refer suspected neglected tropical diseases?',
            'Are the essential diagnostics, medicines and commodities expected for local NTD services available?',
            'Are suspected and confirmed NTD cases recorded and reported through the required surveillance system?',
            'Can patients with NTD-related complications or disability access continuing care, rehabilitation or referral?',
            'Does the facility coordinate with community, vector-control or WASH activities relevant to local NTD prevention and follow-up?',
        ]],
        'BLB' => ['domain' => 'SAFE', 'source' => 'WHO_BLOOD', 'questions' => [
            'Is every donated blood unit screened for the nationally required transfusion-transmissible infections before release?',
            'Are blood grouping, compatibility testing and patient identification completed through documented procedures?',
            'Are blood and blood components stored and transported within monitored temperature requirements?',
            'Can every blood unit be traced from donor or source through testing, storage, issue and recipient?',
            'Are clinical transfusion guidelines used to support appropriate ordering, consent, administration and monitoring?',
            'Are transfusion reactions, errors and near misses investigated and reported through a haemovigilance process?',
        ]],
        'RAD' => ['domain' => 'SERV', 'source' => 'IAEA_RAD_QA', 'questions' => [
            'Does the imaging service operate under the licences and radiation-safety controls required in its jurisdiction?',
            'Are patient identity, examination justification and relevant pregnancy status checked before ionizing-radiation procedures?',
            'Do imaging devices receive documented acceptance testing, quality control and preventive maintenance?',
            'Are staff appropriately qualified and provided with the radiation-protection measures required for their work?',
            'Does the service review image quality, repeat examinations or rejected images and take corrective action?',
            'Are imaging reports delivered within defined time expectations with urgent findings communicated promptly?',
        ]],
        'THR' => ['domain' => 'SAFE', 'source' => 'WHO_SURGERY', 'questions' => [
            'Are surgical and anaesthesia services limited to procedures the facility has the staff, equipment and support to provide safely?',
            'Is a surgical safety checklist used for every operative procedure?',
            'Are patient identity, procedure, consent and operative site confirmed before surgery begins?',
            'Are sterilization, antibiotic prophylaxis and other surgical-site infection prevention processes consistently applied?',
            'Are oxygen, airway equipment, monitoring and essential anaesthesia medicines functional and immediately available?',
            'Are perioperative deaths, complications, returns to theatre and other safety events reviewed for improvement?',
        ]],
        'ADO' => ['domain' => 'PCOM', 'source' => 'WHO_ADOLESCENT', 'questions' => [
            'Can adolescents obtain understandable information about the health services available to them?',
            'Are privacy and confidentiality protected for adolescent consultations within applicable law and safeguarding requirements?',
            'Can adolescents access care without avoidable barriers related to appointments, opening hours or cost?',
            'Are staff trained to provide respectful, non-judgmental and developmentally appropriate adolescent care?',
            'Are adolescents involved in service feedback, monitoring or improvement activities?',
            'Are referral and continuity pathways available for adolescent mental health, sexual and reproductive health, violence and other priority needs?',
        ]],
    ],
];
