services:
  postgres:
    image: postgres:17-alpine
    container_name: vytte_postgres
    environment:
      POSTGRES_DB: vytte
      POSTGRES_USER: vytte
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - vytte_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  vytte_pgdata:
