<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; font-size: 11px; color: #1e293b; line-height: 1.6; }
        .page { padding: 40px 44px; }
        .brand { font-size: 15px; font-weight: 800; color: #0369a1; }
        .label { font-size: 8px; text-transform: uppercase; letter-spacing: 1px; color: #94a3b8; }
        h1 { font-size: 16px; font-weight: 800; color: #0f172a; margin-top: 12px; }
        .sub { font-size: 10px; color: #64748b; margin-top: 2px; margin-bottom: 16px; }
        .body { white-space: pre-line; }
        .foot { margin-top: 28px; border-top: 1px solid #e2e8f0; padding-top: 10px; font-size: 8px; color: #94a3b8; }
    </style>
</head>
<body>
<div class="page">
    <div class="brand">Vytte</div>
    <div class="label">AI summary</div>
    <h1>{{ $title }}</h1>
    @if ($subtitle)
        <p class="sub">{{ $subtitle }}</p>
    @endif
    <div class="body">{{ $body }}</div>
    <div class="foot">
        AI-generated summary — a retelling of the assessment findings for a specific reader. Defer to the full report. Generated by Vytte.
    </div>
</div>
</body>
</html>
