<x-app-layout title="Suggest a question">
    <div class="max-w-3xl">
        <a href="{{ route('contributions.index') }}" class="text-sm text-slate-500 hover:underline">← My contributions</a>
        <h1 class="mt-2 text-xl font-bold text-slate-900 dark:text-white">Suggest an expert question</h1>
        <p class="mt-1 text-sm text-slate-500 dark:text-slate-400">Submission does not make the question public. Reviewers check purpose, source, wording, response design, and reuse before creating a separate draft in the shared library.</p>
        <form method="POST" action="{{ route('contributions.store') }}" class="mt-5 section-card space-y-5 p-6 dark:border-slate-700 dark:bg-slate-800" x-data="{ format: @js(old('response_format', 'yes_no')) }">
            @csrf
            <label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Contribution title<input name="title" value="{{ old('title') }}" required maxlength="180" placeholder="A short name reviewers can recognize" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"></label>
            <label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Suggested department or health area<select name="module_id" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><option value="">Let reviewers decide</option>@foreach ($departments as $department)<option value="{{ $department->module_id }}" @selected((int) old('module_id') === $department->module_id)>{{ $department->module_name }}</option>@endforeach</select></label>
            <label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">Question wording<textarea name="question_text" required rows="3" maxlength="5000" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900">{{ old('question_text') }}</textarea></label>
            <label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">How should people answer?<select name="response_format" x-model="format" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900">@foreach ($formats as $key => $formatInfo)<option value="{{ $key }}">{{ $formatInfo['label'] }}</option>@endforeach</select></label>
            <div x-show="['multiple_choice','multi_select'].includes(format)" class="space-y-2"><p class="text-sm font-semibold text-slate-700 dark:text-slate-200">Answer choices</p>@for ($i=0; $i<6; $i++)<input name="answer_options[]" value="{{ old('answer_options.'.$i) }}" placeholder="Choice {{ $i + 1 }}{{ $i > 1 ? ' (optional)' : '' }}" class="w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900">@endfor</div>
            <div x-show="format === 'number'" class="grid gap-3 sm:grid-cols-3"><input name="numeric_min" type="number" step="any" value="{{ old('numeric_min') }}" placeholder="Minimum" class="rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><input name="numeric_max" type="number" step="any" value="{{ old('numeric_max') }}" placeholder="Maximum" class="rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><input name="numeric_unit" value="{{ old('numeric_unit') }}" placeholder="Unit" class="rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"></div>
            <label class="block text-sm font-semibold text-slate-700 dark:text-slate-200">When and why should this question be used?<textarea name="intended_use" required rows="3" maxlength="3000" class="mt-1.5 w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900">{{ old('intended_use') }}</textarea></label>
            <fieldset class="space-y-3 rounded-xl bg-slate-50 p-4 dark:bg-slate-900/50"><legend class="px-1 text-sm font-semibold text-slate-700 dark:text-slate-200">Source and method</legend><input name="source_authority" value="{{ old('source_authority') }}" placeholder="Source authority or expert group" class="w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><input name="source_url" value="{{ old('source_url') }}" placeholder="Source link (optional)" class="w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><input name="license_code" value="{{ old('license_code') }}" placeholder="Usage permission or licence" class="w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900"><textarea name="methodology_notes" rows="3" placeholder="Evidence, definitions, timeframe, or validation notes" class="w-full rounded-xl border-slate-300 text-sm dark:border-slate-700 dark:bg-slate-900">{{ old('methodology_notes') }}</textarea></fieldset>
            <button class="rounded-xl bg-vytte-600 px-5 py-2.5 text-sm font-semibold text-white">Submit for governed review</button>
        </form>
    </div>
</x-app-layout>
